### ISSUE TITLE
[Question]: About grippers parameter 

### ISSUE THREAD

**Issue by EndlessLoops** [Interbotix/interbotix_ros_manipulators#161]
### Question

 I want to customize a longer gripper without changing too much code.What do these two parameters represent in the arm config？ 

```
grippers:
  gripper:
    horn_radius: 0.014 # ???????????
    arm_length: 0.024 # ???????????
    left_finger: left_finger
    right_finger: right_finger
```
I don't quite understand the meaning of this comment. Does these two parameters have any relation with the initial position of the servo motor? Could you provide an explanatory diagram?

```
    horn_radius: 0.022                                                          # Optional; length in meters from the middle of the gripper servo horn to its edge; defaults to '0.014'
    arm_length: 0.036                                                           # Optional; length in meters from the end of the servo horn to a finger; defaults to '0.024'
```

### Robot Model

v250s

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic
