### ISSUE TITLE
[Question]: Using the gripper servo on the px100 as just another joint

### ISSUE THREAD

**Issue by emmazhou** [Interbotix/interbotix_ros_manipulators#20]
### Question

Hello! I have a px100 on which I've replaced the gripper hardware with a custom-printed part. It looks like (at least from the python library) there's no way to continuously move the gripper servo like the others, only open/close. 

What's the easiest way to treat servo 5 as just another servo, so that it works with e.g. `set_joint_positions`? I've tried editing the config yaml file, but that just confuses the GUI and gave me an index out of bounds error in python.

Thanks!! Otherwise really enjoying playing with the robot so far :)

### Robot Model

px100

### Operating System

A fresh install of Ubuntu 20.04, following instructions from this repo

**Comment by LSinterbotix** [comment]
Hi @emmazhou! There's not an officially supported way to do this, though it is possible. You'll have to create a new "robot" for it to work how you want. Please do the following:

1. Duplicate the [px100 motor config file](https://github.com/Interbotix/interbotix_ros_manipulators/blob/main/interbotix_ros_xsarms/interbotix_xsarm_control/config/px100.yaml) and name it something unique.
2. In the new motor config file, add `gripper` to the list of joints in the `arm` group and remove the list of grippers. Change the configs of the `gripper` joint as needed.
  - The top of your motor config file should look something like:
```yaml
port: /dev/ttyDXL

joint_order: [waist, shoulder, elbow, wrist_angle, gripper]
sleep_positions: [0, -1.88, 1.5, 0.8, 0]

joint_state_publisher:
  update_rate: 100
  publish_states: true
  topic_name: joint_states

groups:
  arm: [waist, shoulder, elbow, wrist_angle, gripper]

shadows:

sisters:

...
```
4. Modify any the px100 URDF (and SRDF if you plan to use MoveIt) so it matches your new arm and name them the same as your motor config file. Make sure to add upper and lower limits to the joint that replaces `gripper`.
5. Create a new class in [mr_descriptions.py](https://github.com/Interbotix/interbotix_ros_toolboxes/blob/main/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/mr_descriptions.py) with the same name as your robot and modify it so it matches the FK of your robot (add a new screw axis row to the Slist and change M so it represents your new "end effector" position and orientation).
6. When creating an InterbotixManipulatorXS object from the Python API, set `gripper_name=None`.

We haven't officially released instructions on anything like this before so there may be some additional steps that we missed. If you encounter any issues, just let us know.
